### ISSUE TITLE
你好，certificate has expired or is not yet valid:

### ISSUE THREAD

**Issue by YakultGo** [hts0000/icode-by-pass#5]
FATAL	无效的icode: Get "https://apis.imooc.com/?cid=108&icode=xxxxxx": x509: certificate has expired or is not yet valid: current time 2023-03-19T14:39:55Z is after 2022-12-28T12:24:33Z

应该怎么解决

**Comment by hts0000** [comment]
证书过期了，当时只生成了1年的时间

**Comment by hts0000** [comment]
根证书已经有了，在ssl目录下，而且已经写入了镜像中，有能力的话自己用根证书重新签发一个server端证书，然后替换server源码里的证书，就可以用了

**Comment by hts0000** [comment]
证书已更新

**Comment by YakultGo** [comment]
> 证书已更新

感谢
