### ISSUE TITLE
大佬你好，请问有Windows下的解决方法吗，毕设最后卡在这了，，，

### ISSUE THREAD

**Issue by changshou83** [hts0000/icode-by-pass#6]
在Ubuntu里运行起来了，但是在Windows中先是报错无效icode，然后我想着把linux里成功运行的容器打包成镜像导入到windows下的docker中运行，结果还是不可以。

然后想着把代码拿到linux下运行，但是微信开发者工具并没有官方linux版本，，所以现在有点尴尬了。。。

**如果有时间的话，希望可以私下交流一下，可以有偿**

拜托了！

**Comment by hts0000** [comment]
Windows里怎么用的？wsl和docker desktop吗

**Comment by changshou83** [comment]
> Windows里怎么用的？wsl和docker desktop吗

感谢大佬深夜回复，是开的虚拟机和docker desktop

**Comment by hts0000** [comment]
> > Windows里怎么用的？wsl和docker desktop吗
> 
> 感谢大佬深夜回复，是开的虚拟机和docker desktop

coolenv容器不需要和启动的服务运行在同一台服务器上，只要服务和coolenv能通信就行。
你可以在虚拟机里运行容器，然后打通虚拟机和宿主机的网络即可

**Comment by changshou83** [comment]
> > > Windows里怎么用的？wsl和docker desktop吗
> > 
> > 感谢大佬深夜回复，是开的虚拟机和docker desktop
> 
> coolenv容器不需要和启动的服务运行在同一台服务器上，只要服务和coolenv能通信就行。
> 你可以在虚拟机里运行容器，然后打通虚拟机和宿主机的网络即可

好的，我今天试试，再次谢谢您的回复

**Comment by changshou83** [comment]
> > > Windows里怎么用的？wsl和docker desktop吗
> > 
> > 
> > 感谢大佬深夜回复，是开的虚拟机和docker desktop
> 
> coolenv容器不需要和启动的服务运行在同一台服务器上，只要服务和coolenv能通信就行。 你可以在虚拟机里运行容器，然后打通虚拟机和宿主机的网络即可

迟来的感谢。
